### PR TITLE
Fix range error

### LINKED ISSUE #426: range error
```
import { range } from "propel"
range(1, 10, 2);
Error: Constructing ndarray of shape (4.5) should match the length of values (4)
    at Object.s [as assert] (http://propelml.org/sandbox.js:25:422)
    at new a (http://propelml.org/sandbox.js:23:407)
    at new o (http://propelml.org/sandbox.js:23:4550)
    at Function.make (http://propelml.org/sandbox.js:23:1382)
    at l.fromTypedArray (http://propelml.org/sandbox.js:117:984)
    at l.range (http://propelml.org/sandbox.js:117:3117)
    at q (http://propelml.org/sandbox.js:234:1399)
    at cell11 top level (cell11:2:1)
```

```
> python
Python 2.7.14 (default, Sep 25 2017, 09:53:22)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.arange(1, 10, 2);
array([1, 3, 5, 7, 9])
```

### PR DESCRIPTION
**Pull request by qti3e**
fix #426

### CODE REVIEW

File: src/api_test.ts [hunk 1]
```diff
@@ -1309,3 +1309,12 @@ test(async function api_size() {
   assert(api.range(20).size === 20);
   assert(api.range(20).reshape([4, 5]).size === 20);
 });
+
+test(async function api_range() {
```
Comment (ry) [inline src/api_test.ts]: There's already a api_range in this file. Please add to that.
