### PR TITLE
cache: Handle URLs with query strings.

### LINKED ISSUE #483: ENOTDIR error when using fetchWithCache
```ts
import { TextDecoder } from "text-encoding";
import * as cache from "./src/api/cache";

async function fetch(url: string) {
  const ab = await cache.fetchWithCache(url);
  const dec = new TextDecoder("ascii");
  return dec.decode(new Uint8Array(ab));
}
async function main() {
  await fetch("https://unpkg.com/sha256@0.2.0/?meta");
  fetch("https://unpkg.com/sha256@0.2.0/lib/nodecrypto.js");
}
main();
```

```
Error: ENOTDIR: not a directory, stat '/home/qti3e/.propel/cache/unpkg.com/sha256@0.2.0/lib'
    at Object.fs.statSync (fs.js:972:11)
    at isDir (/home/qti3e/Projects/propel/src/util_node.ts:21:15)
    at Object.mkdirp (/home/qti3e/Projects/propel/src/util_node.ts:41:8)
    at Object.set (/home/qti3e/Projects/propel/src/cache.ts:115:7)
    at Object.fetchWithCache (/home/qti3e/Projects/propel/src/cache.ts:41:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

```
 qti3e> ls -ltrh ~/.propel/cache/unpkg.com 
total 8.0K
-rw-rw-r-- 1 qti3e qti3e   41 Apr  3 23:06 sha256
-rw-rw-r-- 1 qti3e qti3e 1.6K Apr  3 23:06 sha256@0.2.0
```

(That's because I have already downloaded `https://unpkg.com/sha256@0.2.0/?meta` and now it's saved as a file)

### PR DESCRIPTION
**Pull request by ry**
Fixes #483

### CODE REVIEW

File: src/cache.ts [hunk 1]
```diff
@@ -61,19 +61,18 @@ export function url2Filename(url: string): string {
...
-  const p = encodeURI(u.pathname);
-  assert(p.indexOf("..") < 0, "Safety sanity check");
-  assert(h.indexOf("..") < 0, "Safety sanity check");
   const path = nodeRequire("path");
   // Note we purposely leave the port out of the cache path because
   // Windows doesn't allow colons in filenames. This is probably fine
   // in 99% of cases and is the simplest solution.
-  const cacheFn = path.resolve(path.join(cacheBase(), h, p));
-  assert(cacheFn.startsWith(cacheBase()));
+  const cacheFn = path.resolve(path.join(cacheBase(), h, ...pathnameParts));
```
Comment (piscisaureus) [inline src/cache.ts]: path.resolve takes multiple arguments, no need to path.resolve(path.join(...))

Comment (ry) [reply src/cache.ts]: Fixed.
